services:
  db:
    image: "postgres:16.8-alpine3.20"
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
# docker compose -f infra/compose.yaml up -d
# psql --host=localhost user=postgres
