# workflow: installing dependencies and running scripts npm ci and npm test
name: Automated Tests
on: pull_request # Trigger on pull requests

# Define the jobs that will run in this workflow
jobs:
  prettier:
    name: Prettier
    steps:
      - run: npm ci # Clean install using package-lock.json

      - run: npm run lint:prettier:check # Run Prettier to check formatting
  eslint:
    name: Eslint
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/hydrogen # Specify the Node.js version to use

      - run: npm ci # Clean install using package-lock.json

      - run: npm run lint:eslint:check # Run Prettier to check formatting
